export { default as main } from './main.web'
export { default as despre } from './despre.web'
export { default as unic } from './unic.web'
export { default as about } from './about.web'
export { default as articles } from './articles.web'
export { default as history } from './history.web'
